version: "2"
services:
  athens:
    environment:
     - ATHENS_DISK_STORAGE_ROOT
     - ATHENS_STORAGE_TYPE
     - ATHENS_NETRC_PATH
     - http_proxy
     - https_proxy
     - no_proxy
    image: "$athens_image"
    ports:
     - "3000:3000"
    restart: always
    volumes:
     - /srv/athens:/srv/athens
